In [1]:
#Importing the pacjkages
import timeit
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
import warnings
%matplotlib inline
warnings.filterwarnings('ignore')
#warnings.filterwarnings('always')

In [2]:
# Importing google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# reading the datset
header = ['timestamp', 'value', 'is_anomaly']
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/disease_person_edit.csv', names=header)

In [4]:
df['is_anomaly'] = df['is_anomaly'].round()

In [5]:
df

timestamp  value  is_anomaly
0      05:57.0    433         0.0
1      05:57.0    430         0.0
2      05:57.0    427         0.0
3      05:57.0    426         0.0
4      05:57.0    427         0.0
...        ...    ...         ...
9710   06:47.4    574         0.0
9711   06:47.4    560         0.0
9712   06:47.5    547         0.0
9713   06:47.5    529         0.0
9714   06:47.5    509         0.0

[9715 rows x 3 columns]

In [6]:
x = df.drop('is_anomaly', axis=1)
y = df['is_anomaly'] 


In [7]:
x = x.drop('timestamp', axis=1)

In [8]:
x.shape

(9715, 1)

In [9]:
import numpy as np
from sklearn                        import metrics, svm
from sklearn.linear_model           import LinearRegression
from sklearn.linear_model           import LogisticRegression
from sklearn.tree                   import DecisionTreeClassifier
from sklearn.neighbors              import KNeighborsClassifier
from sklearn.discriminant_analysis  import LinearDiscriminantAnalysis
from sklearn.naive_bayes            import GaussianNB
from sklearn.svm                    import SVC

In [10]:
clf = LinearRegression()
clf.fit(x, y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
d = clf.predict(x)

In [12]:
d

array([0.00424384, 0.0042031 , 0.00416237, ..., 0.00579174, 0.00554734,
       0.00527577])

In [13]:
pred = d.round()

In [14]:
pred

array([0., 0., 0., ..., 0., 0., 0.])

In [19]:
df['anomaly'] = d.round()

In [20]:
df.head()

timestamp  value  is_anomaly  anomaly
0   05:57.0    433         0.0      0.0
1   05:57.0    430         0.0      0.0
2   05:57.0    427         0.0      0.0
3   05:57.0    426         0.0      0.0
4   05:57.0    427         0.0      0.0

In [15]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00      9664
         1.0       0.00      0.00      0.00        51

    accuracy                           0.99      9715
   macro avg       0.50      0.50      0.50      9715
weighted avg       0.99      0.99      0.99      9715



In [16]:
conf = confusion_matrix(y, pred)
conf

array([[9664,    0],
       [  51,    0]])

In [21]:
anomaly=df.loc[df['anomaly']==1]
anomaly_index=list(anomaly.index)
print(anomaly)

Empty DataFrame
Columns: [timestamp, value, is_anomaly, anomaly]
Index: []
