In [ ]:
#Importing the pacjkages
import timeit
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
import warnings
%matplotlib inline
warnings.filterwarnings('ignore')
#warnings.filterwarnings('always')

In [ ]:
# Importing google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# reading the datset
header = ['timestamp', 'value', 'is_anomaly']
df=pd.read_csv('/content/drive/MyDrive/suraj/disease_person_edit.csv', names=header)

In [ ]:
df['is_anomaly'] = df['is_anomaly'].round()

In [ ]:
df

timestamp  value  is_anomaly
0      05:57.0    433         0.0
1      05:57.0    430         0.0
2      05:57.0    427         0.0
3      05:57.0    426         0.0
4      05:57.0    427         0.0
...        ...    ...         ...
9710   06:47.4    574         0.0
9711   06:47.4    560         0.0
9712   06:47.5    547         0.0
9713   06:47.5    529         0.0
9714   06:47.5    509         0.0

[9715 rows x 3 columns]

In [ ]:
x = df.drop('is_anomaly', axis=1)
y = df['is_anomaly'] 


In [ ]:
x = x.drop('timestamp', axis=1)

In [ ]:
x.shape

(9715, 1)

In [ ]:
import numpy as np
from sklearn                        import metrics, svm
from sklearn.linear_model           import LinearRegression
from sklearn.linear_model           import LogisticRegression
from sklearn.tree                   import DecisionTreeClassifier
from sklearn.neighbors              import KNeighborsClassifier
from sklearn.discriminant_analysis  import LinearDiscriminantAnalysis
from sklearn.naive_bayes            import GaussianNB
from sklearn.svm                    import SVC

In [ ]:
clf = svm.SVR()
clf.fit(x, y)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
d = clf.predict(x)

In [ ]:
d

array([0.1, 0.1, 0.1, ..., 0.1, 0.1, 0.1])

In [ ]:
pred = d.round()

In [ ]:
pred

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00      9664
         1.0       0.00      0.00      0.00        51

    accuracy                           0.99      9715
   macro avg       0.50      0.50      0.50      9715
weighted avg       0.99      0.99      0.99      9715



In [ ]:
conf = confusion_matrix(y, pred)
conf

array([[9664,    0],
       [  51,    0]])